--
-- One Identity - Open Source License
--
-- Copyright 2018 One Identity LLC
--
-- Permission is hereby granted, free of charge, to any person obtaining a copy of
-- this software and associated documentation files (the "Software"), to deal in
-- the Software without restriction, including without limitation the rights to
-- use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
-- of the Software, and to permit persons to whom the Software is furnished to do
-- so, subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in all
-- copies or substantial portions of the Software. Any and all copies of the above
-- copyright and this permission notice contained in the Software shall not be
-- removed, obscured, or modified.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-- SOFTWARE.
--

--
-- ONE IDENTITY LLC. PROPRIETARY INFORMATION
--
-- This software is confidential.  One Identity, LLC. or one of its affiliates or
-- subsidiaries, has supplied this software to you under terms of a
-- license agreement, nondisclosure agreement or both.
--
-- You may not copy, disclose, or use this software except in accordance with
-- those terms.
--
--
-- Copyright 2017 One Identity LLC.
-- ALL RIGHTS RESERVED.
--
-- ONE IDENTITY LLC. MAKES NO REPRESENTATIONS OR
-- WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE,
-- EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
-- TO THE IMPLIED WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE, OR
-- NON-INFRINGEMENT.  ONE IDENTITY LLC. SHALL NOT BE
-- LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE
-- AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
-- THIS SOFTWARE OR ITS DERIVATIVES.
--
-- 7.1 SP 3
